# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CheckPlusPlus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CheckPlusPlus
  ## ReactiveX
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'
  
  ## Network
  pod 'CocoaAsyncSocket'
  
  ## Protobuf
  pod 'SwiftProtobuf', '~> 1.0'
  
  ## Auth
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/OAuth'
  
  ## Animation
  pod 'lottie-ios'
  
  ## Keychain
  pod 'KeychainSwift', '~> 19.0'
end
